name: ✨Features Template
description: Template for feature requests
title: "[FEATURES] "
labels: enhancement
type: feature
body:
  - type: textarea
    id: feature_background
    attributes:
        label: '새로운 기능을 제안한 배경'
        description: '이 기능이 필요하다고 느낀 이유를 구체적으로 설명해주세요.'
        placeholder: '예: ~~한 상황에서 ~~한 기능이 있었으면 좋겠다고 생각했습니다.'
    validations:
        required: true

  - type: textarea
    id: feature_description
    attributes:
        label: '기능 설명'
        description: '제안하는 기능이 무엇인지 구체적으로 설명해주세요.'
        placeholder: '예: 이 기능은 ~~한 동작을 수행하며, ~~한 결과를 제공합니다.'
    validations:
        required: true

  - type: textarea
    id: feature_benefits
    attributes:
        label: '기대 효과'
        description: '이 기능이 구현되었을 때 기대되는 효과나 이점을 구체적으로 설명해주세요.'
        placeholder: '예: 이 기능을 통해 ~~한 문제를 해결할 수 있습니다.'
    validations:
        required: true

  - type: textarea
    id: additional_info
    attributes:
        label: '추가 내용'
        description: '추가적인 고려 사항에 대해 작성해주세요.'
        placeholder: '예: 이 기능은 특정 네트워크 환경에서만 필요합니다.'
    validations:
        required: false

  - type: textarea
    id: references
    attributes:
        label: '참고 자료'
        description: '관련된 문서, 링크, 이미지 등을 첨부해주세요.'
        placeholder: '예: API 문서 링크, 디자인 시안 이미지 등'
    validations:
        required: false
